[package]
name = "rust-cross-compile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.22.0"
iced = "0.9.0"
iced_aw = { version = "0.5", default-features = false, features = ["menu", "split", "tab_bar", "tabs"] }
log = "0.4.18"
pretty_env_logger = "0.5"
rfd = "0.11.4"
