name: Build and Create AppImage

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform:
          - linux
          - macos
          - windows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install Dependencies
        if: matrix.platform == 'linux'
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev librust-atk-dev

      - name: Build Binary
        run: cargo build --release

      - name: Create AppImage (Linux)
        if: matrix.platform == 'linux'
        run: |
          wget -O appimagetool.AppImage https://github.com/AppImage/AppImageKit/releases/latest/download/appimagetool-x86_64.AppImage
          chmod +x appimagetool.AppImage
          mkdir -p appdir/usr/bin
          cp target/release/my-project appdir/usr/bin
          ./appimagetool.AppImage appdir

      - name: Archive Artifacts
        if: matrix.platform == 'linux'
        uses: actions/upload-artifact@v2
        with:
          name: my-project-appimage
          path: my-project-x86_64.AppImage
