name: Build

on: 
  push:
    branches: [ '**' ]

jobs:
  release:
    name: ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: my-project
            command: build

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: my-project
            command: both

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: my-project.exe
            command: both

            # more release targets here ...

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2

      - name:  Install
        run: |
          if [ "$RUNNER_OS" == 'Linux' ]; then
            sudo add-apt-repository universe && sudo apt install -y libgtk-3-dev librust-atk-dev libfuse2 appstreamcli
          fi
        shell: bash
      
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--release"
          strip: true

      - name: Create AppImage (Linux)
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            wget -O appimagetool.AppImage https://github.com/AppImage/AppImageKit/releases/latest/download/appimagetool-x86_64.AppImage
            chmod +x appimagetool.AppImage
            mkdir -p appdir/usr/bin
            cp target/x86_64-unknown-linux-gnu/release/my-project appdir/usr/bin
            ./appimagetool.AppImage appdir
          fi
        shell: bash

      - name: Archive Artifacts
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: my-project-appimage
          path: my-project-x86_64.AppImage

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-project-${{ matrix.platform.target }}
          path: ./target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
