name: Clippy

on: 
  push:
    branches: [ '**' ]

jobs:
  build:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install
        run: |
          sudo apt install -y libgtk-3-dev librust-atk-dev
        shell: bash

      - uses: Swatinem/rust-cache@v2

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Run Clippy
        run: cargo clippy -- -D warnings
