name: Clippy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  build:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Run Clippy
        run: cargo clippy -- -D warnings
