name: Upload Artifacts to Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: ./.github/workflows/build.yml

  upload_artifacts:
    name: Upload Artifacts to Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml

      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          file: "*.md"
          tags: true
          draft: true
